[Build] Add bootstrap.sh
K3S-prod/k3s-virtual-machine pull request #3
Opened 2022-12-12 12:52 UTC by sin-diesel

Add script for libs installation
﻿

2022-12-12 13:08 UTC, sin-diesel commented
Fixes https://github.com/K3S-prod/k3s-virtual-machine/issues/1

2022-12-12 13:18 UTC, dkofanov approved these changes

2022-12-12 13:19 UTC, dkofanov requested changes
I think it is better to squash the commits

2022-12-12 13:48 UTC, sin-diesel reviewed
Also added branch protection rules

2022-12-13 01:43 UTC, dkofanov approved these changes

2022-12-13 04:04 UTC, merged